---
- hosts: swarm-master-1
  become: true

  tasks:
    - name: Initialize the cluster
      shell: sudo apt update; sudo apt install -y docker; sudo systemctl start docker; sudo curl -sSL https://get.docker.com/ | sh; sudo docker swarm init --advertise-addr 192.168.77.10 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
